sudo: false

language: node_js
node_js:
  - 10

addons:
  ssh_known_hosts: 82.202.226.188

branches:
  only:
    - master

script: npm run build

after_script:
  - rsync -r --delete-after --quiet build $SSH_USER:$SSH_PASSWORD@$SSH_HOST:$DEPLOY_PATH